---
- hosts: all
  gather_facts: false
  vars:
    deploy_folder: "../deploy"

  tasks:

    - name: "Get code from Github ({{ git_branch }} branch)"
      local_action:
        module: git
        repo: "git@github.com:UniversityofHelsinki/sopimusportaali.git"
        dest: "{{ deploy_folder }}"
        version: "{{ git_branch }}"
        force: yes
        depth: 1

    - name: "Build codebase for {{ project_env }} environment"
      local_action: "command composer run-script build-{{ project_env }}"
      args:
        chdir: "{{ deploy_folder }}"

    - name: Create release artifact
      local_action: "command composer run-script artifact"
      args:
        chdir: "{{ deploy_folder }}"

    - name: Gather facts about remote
      setup:

    - name: Get timestamp for the release
      set_fact: timestamp="{{ ansible_date_time.epoch }}"

    - block:

        - name: Make sure releases folder exists
          file:
            path: "{{ projects.default.root }}/releases/{{ timestamp }}"
            state: directory
            mode: 0755

        - name: "Extract artifact into {{ projects.default.root }}/releases/{{ timestamp }}"
          unarchive:
            src: "{{ deploy_folder }}/artifact.tar.gz"
            dest: "{{ projects.default.root }}/releases/{{ timestamp }}"

        - name: "Make sure release has correct permissions"
          file:
            dest: "{{ projects.default.root }}/releases/{{ timestamp }}"
            owner: "{{ nginx_user }}"
            group: "{{ nginx_group }}"
            mode: 0775
            recurse: yes

        - name: "Set symlinks"
          file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
          with_items:
            - { src: "{{ projects.default.root }}/releases/{{ timestamp }}/public", dest: "{{ projects.default.public_root }}" }
            - { src: "{{ projects.default.root }}/shared/settings.local.php", dest: "{{ projects.default.public_root }}/sites/default/settings.local.php" }
            - { src: "{{ projects.default.root }}/shared/files", dest: "{{ projects.default.public_root }}/sites/default/files" }

      become: yes

    # Executes drush commands
    - name: Run drush commands
      shell: drush -y -r {{ projects.default.public_root }} {{ item }}
      with_items:
        # Performs database updates.
        - "updb"
        # Clears caches.
        - "cr"
        # Imports configuration changes.
        - "cim -y"
